function [oceanLimit, latlim, lonmin] = ...
        findoceanboundary(oceanNames, inclang, lonOrigin)
    LimitsOfOceansAndSeas = limitsofoceansandseas;
    oceanLimit = union( ...
        [LimitsOfOceansAndSeas( ...
         ismember({LimitsOfOceansAndSeas.Name}, oceanNames) ...
     ).poly]);

    oceanLimit = simplify(oceanLimit);
    [lon, lat] = poly2cw( ...
        oceanLimit.Vertices(:, 1), oceanLimit.Vertices(:, 2));

    [lon, lat] = closecoastline(lon, lat);
    [lat, lon] = flatearthpoly( ...
        lat, lon, lonOrigin);

    oceanLimit = polyshape(lon, lat);
    oceanLimit = removepolarcaps(oceanLimit, inclang, lonOrigin);
    latlim = ...
        [min(oceanLimit.Vertices(:, 2)), ...
         max(oceanLimit.Vertices(:, 2))];
    lonmin = ...
        [min(oceanLimit.Vertices(:, 1)), ...
         max(oceanLimit.Vertices(:, 1))];
end
